alias tmux='TERM=xterm-256color tmux -2'
alias tmuxinator='TERM=xterm-256color tmuxinator'
alias mux='TERM=xterm-256color mux'
alias vim='TERM=xterm-256color vim'
alias gitl='git log --full-history --all --color --pretty=format:"%C(auto)%h %ad %Cblue%<(25)%an%Creset%C(auto) %gs%d%s" --date=local --date=short'
